version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
      #expose:
      # -27017

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - DB_HOST=host.docker.internal
      # - DB_PORT=27017
      # - DB_HOST=db
