services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
      #expose:
      # -27017
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    restart: unless-stopped
    environment:
      - MONGODB_URI=host.docker.internal
      - URL_CLIENT=http://localhost
      # - DB_PORT=27017
      # - DB_HOST=db
  nginx:
    image: nginx:1.25.5
    ports:
      - 80:80
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
